export { default as InstituteDashboard } from './Dashboard'
export { default as StudentDetail } from './StudentDetail'
export { default as Student } from './Student'
export { default as Create } from './Create'
export { default as Departments } from './Departments'
export { default as FacultyDetails } from './FacultyDetails'
export {default as Course} from './Course'
export {default as Faculty} from './Faculty'